name: version-bump
on:
  push:
    branches:
      - master
      - main
      - rc
      - dev

jobs:
  create-version-tag:
    if: ${{ !contains(github.event.head_commit.message, '#skip_next_version') }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Set ENVs
        run: |
          echo "PRERELEASE_SUFFIX=${{ github.head_ref || github.ref_name }}" >> "$GITHUB_ENV"
          if [[ "${{ github.head_ref || github.ref_name }}" == "dev" ]]; then echo "PRERELEASE=true" >> "$GITHUB_ENV"; fi
          if [[ "${{ github.head_ref || github.ref_name }}" == "rc" ]]; then echo "PRERELEASE=true" >> "$GITHUB_ENV"; fi
          if [[ "${{ github.head_ref || github.ref_name }}" == "master" ]]; then echo "PRERELEASE=false" >> "$GITHUB_ENV"; fi
          if [[ "${{ github.head_ref || github.ref_name }}" == "main" ]]; then echo "PRERELEASE=false" >> "$GITHUB_ENV"; fi

      - name: Get next version
        id: next-version
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          PRERELEASE: ${{ env.PRERELEASE }}
          PRERELEASE_SUFFIX: ${{ env.PRERELEASE_SUFFIX }}
          DEFAULT_BUMP: patch
          DRY_RUN: true

      - name: Determine if new tag differs
        id: tag-check
        env:
          OLD_TAG: ${{ steps.next-version.outputs.old_tag }}
          NEW_TAG: ${{ steps.next-version.outputs.new_tag }}
        run: |
          echo "::notice::OLD_TAG=$OLD_TAG"
          echo "::notice::NEW_TAG=$NEW_TAG"
          if [ "$OLD_TAG" = "$NEW_TAG" ]; then
            echo "::notice::tags are equal; no change"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "::notice::tags differ; will update"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Update version in package.json
        if: ${{ steps.tag-check.outputs.changed == 'true' }}
        run: |
          git config --local user.email "panterobot@gisat.cz"
          git config --local user.name "github-actions[bot]"
          npm version ${{ steps.next-version.outputs.new_tag }} -m "Set package.json version to ${{ steps.next-version.outputs.new_tag }} #skip_next_version"

      - name: Push changes
        if: ${{ steps.tag-check.outputs.changed == 'true' }}
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
